name: fading_text_animation
description: "A new Flutter project that animates fading text."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0" # Ensure compatibility with the current stable version of Flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  window_size: ^0.1.0
  flutter_colorpicker: ^1.1.0
  expressions: ^0.3.4 # Add this line for the expressions package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
